### ISSUE TITLE
how to convert the compartment unit and particle number into molarity

### ISSUE THREAD

**Issue by vibha15** [CiaranWelsh/pycotools3#3]
Hi Mr Welsh,
I am again stuck in building model in pycotools3.  Generally, it builds the model  with mol as species's concentration and liters as compartment unit. I need to convert the compartment unit in femtoliters and species in nmol. 
I build models using antimony. I have gone through pycotools3 master's documentation and found the conversion documentation for species. But i am not sure how to apply these in building models. I am seeking your suugestions in this regard.

Thank you for your time and help.

Vibha

<img width="1280" alt="convert_units" src="https://user-images.githubusercontent.com/52018214/62724058-bb1f2b00-b9d7-11e9-9112-8f9154b49ba6.png">

**Comment by CiaranWelsh** [comment]
Hey Vibha, 

I'm sure I've built a mechanism for changing model units into pycotools (I think its a property of the model.Model class. Try `dir(mod)` to checkout which methods the `model.Model` has),  

However, I think the easiest way to do this would be on model definition itself. i.e. via antimony [here](https://tellurium.readthedocs.io/en/latest/antimony.html#units). 

In general, I've found that a good way to understand antimony is: build the feature you are unsure of in a toy copasi model. Maybe you set the units to what you want or want to include a fixed component. Then export the sbml from copasi and use [telluriums SBMLToAntimony](https://tellurium.readthedocs.io/en/latest/_modules/tellurium/tellurium.html#SBMLToantimony) function. I find the auto-generated code too cumbersome to work with all of the time, but its a good way of understanding what you can do with antimony. 

Hopefully this helps, good luck, 

Ciaran

**Comment by vibha15** [comment]
Thank you so much Mr Welsh! I will go ahead accordingly and see. Thanks for your time.

Vibha
________________________________
