### ISSUE TITLE
Pip installation failing with dependencies 

### ISSUE THREAD

**Issue by gmarupilla** [CiaranWelsh/pycotools3#5]
`pip install pycotools3` getting installation error, which throwing out `No matching distribution for tesbml>=5.15.0.1 (from tellurium->pycotools3) (from versions: none)`

**Comment by CiaranWelsh** [comment]
Hi gmarupilla, 

Which version of python are you using? There are known issues with the tellurium dependency not working properly on Python 3.7 or 3.8. If you are not using Python 3.6 try creating a environment using virtualenv or conda. My preference is conda:
```
$ conda create --name py36 python=3.6
```
then switch to it using
```
$ conda activate py36
```
and try again
```
$ pip install pycotools3
```
I have tried this on a clean environment and it works fine for me. 

Ciaran
